use_frameworks!

platform :ios, '14.0'

target 'AppsOnAir-AppRemark_Example' do
  pod 'AppsOnAir-AppRemark', :path => '../'

  
  target 'AppsOnAir-AppRemark_Tests' do
    inherit! :search_paths


  end
end
